server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/HB?characterEncoding=utf-8
    username: root
    password: QCqincong115qc
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 3000
      connection-test-query: SELECT 1
      pool-name: HurpodsHikariCP
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
